name: Run Project
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout
      - name: Check node.js
        uses: actions/setup-node
        with:
          node-version: 21
      - name: Install dependencies
        run: npm install
      - name: Project Run
        run: npm run dev
